datamodule:
  batch_size: 256
  shuffle: True
  val_batch_size: 50

model:
  hidden_size: 128
  heads: 8
  normalise: True
  att_dropout: 0.0
  edge_dropout: 0.0

regressor:
  noise: null
  lr: 3.0e-4
  weight_decay: 0.0001
  log_norm: False
  min_dist: 20
  edge_weight: True

trainer:
  check_val_every_n_epoch: 2
  max_epochs: 20
  deterministic: True

logger:
  offline: False
  version: gat_edge_02
  project: trajectory_forecasting_gat

misc:
  seed: 1
  model_type: GATGNN
  dm_type: OneStepNBodyDataModule
  regressor_type: OneStepModule
  checkpoint: False
  train: True
  continue_training: null
