datamodule:
  batch_size: 64
  shuffle: True
  val_batch_size: 50

model:
  hidden_size: 256
  normalise: True
  edge_dropout: 0.0
  latent_edge_features: 0
  edge_features: 1
  skip: True

regressor:
  noise: null
  lr: 1.0e-3
  weight_decay: 0.0
  log_norm: False
  min_dist: 20
  grav_attraction: False
  edge_weight: True
  self_loop: False
  undirected: False

trainer:
  check_val_every_n_epoch: 1
  max_epochs: 20
  deterministic: True

logger:
  offline: True
  version: gcn_redodododo
  project: trajectory_forecasting_gcn

misc:
  seed: 1
  model_type: conv_model
  dm_type: OneStepNBodyDataModule
  regressor_type: OneStepModule
  train: True
  checkpoint: False
  continue_training: null


