datamodule:
  batch_size: 1
  shuffle: True

model:
  hidden_size: 256
  gru_dim: 20
  normalise: True

regressor:
  noise: 0.01
  lr: 3.0e-4
  weight_decay: 0.001
  log_norm: False

trainer:
  check_val_every_n_epoch: 2
  max_epochs: 20
  #max_steps: 1
  deterministic: True
  num_sanity_val_steps: 2


logger:
  offline: False
  version: grugnn_v1_04
  project: trajectory_forecasting_sequential

misc:
  seed: 1
  model_type: GRUGNN
  dm_type: SequentialNBodyDataModule
  regressor_type: SequentialModule
  checkpoint: True
  train: True
