datamodule:
  batch_size: 64
  shuffle: True
  val_batch_size: 50

model:
  hidden_size: 256
  normalise: True
  dropout: 0.5
  latent_edge_features: 128
  edge_features: 2
  skip: True
  aggregate: False

regressor:
  noise: 3.0e-4
  lr: 1.0e-5
  weight_decay: 0.001
  log_norm: False
  min_dist: null
  edge_weight: True
  grav_attraction: True
  self_loop: False
  undirected: False

trainer:
  check_val_every_n_epoch: 1
#  max_epochs: 25
  deterministic: True
  max_steps: 1

logger:
  offline: True
  version: fc_mlp_bigdata_02
  project: trajectory_forecasting_meeting

misc:
  seed: 1
  model_type: mlp_full_forward_model
  dm_type: OneStepNBodyDataModule
  regressor_type: OneStepModule
  checkpoint: False
  train: True
  continue_training: null #trajectory_forecasting_mlp_forward_model/test_for_new_data_real_grav_4/checkpoints/epoch=19-step=14079.ckpt
