datamodule:
  batch_size: 64
  shuffle: True
  val_batch_size: 50

model:
  hidden_size: 128
  normalise: True
  dropout: 0.50
  latent_edge_features: 128
  edge_features: 2
  rounds: 5
  shared_params: False

regressor:
  noise: 0.0001
  lr: 1.0e-5
  weight_decay: 0.001
  log_norm: False
  min_dist: null
  edge_weight: True
  grav_attraction: True
  self_loop: False
  undirected: False

trainer:
  check_val_every_n_epoch: 1
  max_epochs: 40
  deterministic: True

logger:
  offline: False
  version: mpnn_run_v02_05_bd
  project: trajectory_forecasting_mlp_forward_model

misc:
  seed: 1
  model_type: mpnn_forward_model
  dm_type: OneStepNBodyDataModule
  regressor_type: OneStepModule
  checkpoint: False
  train: True
  continue_training: null #trajectory_forecasting_mlp_forward_model/test_for_new_data_real_grav_4/checkpoints/epoch=19-step=14079.ckpt
