datamodule:
  batch_size: 25
  shuffle: True
  val_batch_size: 50

model:
  hidden_size: 256
  rnn_size: 64
  normalise: True
  dropout: 0.5
  edge_dropout: 0.5
  num_layers: 1

regressor:
  noise: 0.1
  lr: 1.0e-3
  weight_decay: 0.0
  log_norm: False
  teacher_forcing: True
  teacher_forcing_ratio: 0.2 # % of time to use groundtruth batch
  min_dist: 20
  edge_weight: True

trainer:
  check_val_every_n_epoch: 1
  max_epochs: 30
  deterministic: True
  log_every_n_steps: 10

logger:
  offline: False
  version: rnn_34
  project: trajectory_forecasting_rnn

misc:
  seed: 1
  model_type: RNNGNN
  dm_type: SequentialNBodyDataModule
  regressor_type: SequentialModule
  checkpoint: True
  train: True
  continue_training: null #trajectory_forecasting_rnn/rnn_29/checkpoints/epoch=29-step=599.ckpt

