noise: null
lr: 1.0e-3
weight_decay: 0.0
min_dist: 30
n_neighbours: 6
edge_weight: True
grav_attraction: False
self_loop: False
undirected: False
teacher_forcing_ratio: 0.0
node_features: 5
edge_features: 1
out_features: 4
training_horizon: 51
fully_connected: False