check_val_every_n_epoch: 2
max_epochs: 25
deterministic: False
num_sanity_val_steps: 2
precision: 32 # Default. Only available on GPU.
gpus: 0
default_root_dir: logs
detect_anomaly: False
gradient_clip_val: 0.5