datamodule:
  batch_size: 8
  shuffle: true
  val_batch_size: 8
model:
  hidden_size: 128
  dropout: 0.0
  latent_edge_features: 16
  node_features: 7
  edge_features: 1
  skip: true
  aggregate: false
  out_features: 2
regressor:
  out_features: 4
  noise: null
  lr: 0.001
  weight_decay: 0.0
  min_dist: 10
  n_neighbours: 20
  edge_weight: true
  normalise: true
  node_features: 7
  edge_features: 1
  teacher_forcing_ratio: 0.0
  prediction_horizon: 51
  training_horizon: 50
  edge_dropout: 0.0
trainer:
  check_val_every_n_epoch: 1
  max_epochs: 70
  deterministic: false
  num_sanity_val_steps: 2
  precision: 32
  val_check_interval: 1.0
  gpus: 1
  default_root_dir: logs
  detect_anomaly: false
  gradient_clip_val: 5.0
logger:
  offline: false
  version: MPGNN_03
  project: Waymo_finalised_results
  name: MPGNN_03
misc:
  seed: 2
  model_type: MPGNN
  dm_type: SequentialWaymoDataModule
  regressor_type: WaymoModule
  train: true
  validate: true
  test: true
  log_freq: 10
