check_val_every_n_epoch: 1
max_epochs: 1
deterministic: True
num_sanity_val_steps: 2
precision: 32 # Default. Only available on GPU.
val_check_interval: 0.50 # Default 1.0
gpus: 1
default_root_dir: logs
detect_anomaly: False