datamodule:
  batch_size: 25
  shuffle: True
  val_batch_size: 50

model:
  hidden_size: 128
  normalise: True
  dropout: 0.5
  edge_features: 0
  skip: True
  rnn_size: 64
  num_layers: 1
  latent_edge_features: 0

regressor:
  noise: 0.0001
  lr: 1.0e-3
  weight_decay: 0.001
  log_norm: False
  min_dist: null
  edge_weight: False
  self_loop: False
  undirected: False
  teacher_forcing: True
  teacher_forcing_ratio: 0.2
  rnn_type: LSTM
  grav_attraction: False

trainer:
  check_val_every_n_epoch: 1
  max_epochs: 40
  deterministic: True
  log_every_n_steps: 10

logger:
  offline: false
  version: rnn_baseline_graph_02
  project: trajectory_forecasting_rnn_baseline

misc:
  seed: 1
  model_type: rnn_graph_baseline
  dm_type: SequentialNBodyDataModule
  regressor_type: SequentialModule
  checkpoint: False
  train: True
  continue_training: null
