datamodule:
  batch_size: 25
  shuffle: True
  val_batch_size: 50

model:
  normalise: True
  dropout: 0.5
  rnn_size: 128
  K: 2
  edge_dropout: 0.0

regressor:
  noise: null
  lr: 3.0e-4
  weight_decay: 0.0001
  log_norm: False
  teacher_forcing: True
  teacher_forcing_ratio: 0.3 # % of time to use groundtruth batch
  min_dist: 20
  edge_weight: True

trainer:
  check_val_every_n_epoch: 1
  max_epochs: 10
  deterministic: True
  log_every_n_steps: 10
  num_sanity_val_steps: 0

logger:
  offline: False
  version: gconvlstm_27_edgeweight
  project: trajectory_forecasting_rnn

misc:
  seed: 1
  model_type: GConvLSTMGNN
  dm_type: SequentialNBodyDataModule
  regressor_type: SequentialModule
  checkpoint: False
  train: True
  continue_training: null

