datamodule:
  batch_size: 64
  shuffle: True
  val_batch_size: 50

model:
  hidden_size: 128
  normalise: True
  dropout: 0.5
  edge_dropout: 0.0
  latent_edge_features: 32
  edge_model: MPNN_edge_model

regressor:
  noise: null
  lr: 1.0e-3
  weight_decay: 0.0
  log_norm: False
  min_dist: 20
  edge_weight: True
  self_loop: False
  undirected: False

trainer:
  check_val_every_n_epoch: 1
#  max_epochs: 10
  max_steps: 10000
  deterministic: True
  #log_every_n_steps: 10

logger:
  offline: False
  version: mpnn_16_good
  project: trajectory_forecasting_mpnn

misc:
  seed: 0
  model_type: MPNN_node_model
  dm_type: OneStepNBodyDataModule
  regressor_type: OneStepModule
  checkpoint: True
  train: True
  continue_training: null

