datamodule:
  batch_size: 25
  shuffle: True
  val_batch_size: 50

model:
  hidden_size: 128
  normalise: True
  dropout: 0.5
  edge_features: 2
  skip: True
  rnn_size: 64
  num_layers: 1
  latent_edge_features: 64

regressor:
  noise: 0.0001
  lr: 1.0e-4
  weight_decay: 0.001
  log_norm: False
  min_dist: 30
  edge_weight: True
  self_loop: False
  undirected: False
  teacher_forcing: True
  teacher_forcing_ratio: 0.2
  rnn_type: GRU
  grav_attraction: True

trainer:
  check_val_every_n_epoch: 1
  max_epochs: 20
  deterministic: True
  log_every_n_steps: 10

logger:
  offline: False
  version: node_rnn_06
  project: trajectory_forecasting_rnn_forward_model

misc:
  seed: 1
  model_type: rnn_node_forward_model
  dm_type: SequentialNBodyDataModule
  regressor_type: SequentialModule
  checkpoint: False
  train: True
  continue_training: null
