defaults:
  - datamodule: sequential
  - model: mlp_forward
  - regressor: sequential
  - trainer: sequential
  - _self_

logger:
  offline: False
  version: ???
  project: ???


misc:
  seed: 1
  model_type: mlp_full_forward_model
  dm_type: SequentialWaymoDataModule
  regressor_type: SequentialModule
  train: True
  log_freq: 10

hydra:
  output_subdir: null
  run:
    dir: .

