defaults:
  - datamodule: onestep
  - model: mlp_forward
  - regressor: onestep
  - trainer: onestep
  - _self_

logger:
  offline: False
  version: ???
  project: meeting_nov_09

misc:
  seed: 1
  model_type: mlp_full_forward_model
  dm_type: OneStepWaymoDataModule
  regressor_type: OneStepModule
  checkpoint: False
  train: True
  continue_training: null

hydra:
  output_subdir: null
  run:
    dir: .
