defaults:
  - datamodule: onestep
  - model: mlp_forward
  - regressor: onestep
  - trainer: onestep
  - ckpt_path: null
  - sequence_idx: null
  - _self_

logger:
  offline: False
  version: ???
  project: ???


misc:
  seed: 1
  model_type: mlp_full_forward_model
  dm_type: OneStepWaymoDataModule
  regressor_type: OneStepModule
  checkpoint: False
  train: True
  continue_training: null
  ckpt_path: null
  sequence_idx: null
  log_freq: 10

hydra:
  output_subdir: null
  run:
    dir: .
