datamodule:
  batch_size: 64
  shuffle: True

regressor:
  noise: null
  out_features: 6

trainer:
  check_val_every_n_epoch: 2
  max_epochs: 20
  deterministic: True

logger:
  offline: True
  version: baseline

misc:
  seed: 1
  model_type: ConstantModel
  dm_type: OneStepWaymoDataModule
  regressor_type: ConstantPhysicalBaselineModule
  train: False
  checkpoint: False
  continue_training: null


