datamodule:
  batch_size: 64
  shuffle: True
  val_batch_size: 25

model:
  hidden_size: 64
  dropout: 0.5
  latent_edge_features: 64
  node_features: 15
  edge_features: 1
  skip: True
  aggregate: False
  out_features: 7

regressor:
  out_features: 7
  noise: 1.0e-3
  lr: 1.0e-5
  weight_decay: 0.0001
  edge_type: knn
  min_dist: 0
  n_neighbours: 15
  edge_weight: True
  fully_connected: True
  self_loop: False
  undirected: False
  normalise: True
  node_features: 15
  edge_features: 1

trainer:
  check_val_every_n_epoch: 1
  max_epochs: 3
  deterministic: True
  num_sanity_val_steps: 0
  limit_train_batches: 0.01 # Default 1.0
  precision: 32 # Default. Only available on GPU.
#  val_check_interval: 0.50 # Default 1.0
  gpus: 1

logger:
  offline: False
  version: full_run_10
  project: waymo_forwardmodel

misc:
  seed: 1
  model_type: mlp_full_forward_model
  dm_type: OneStepWaymoDataModule
  regressor_type: OneStepModule
  checkpoint: False
  train: True
  continue_training: null
