datamodule:
  batch_size: 32
  shuffle: True
  val_batch_size: 25

model:
  hidden_size: 64
  normalise: True
  dropout: 0.5
  latent_edge_features: 64
  node_features: 9
  edge_features: 1
  skip: True
  aggregate: False
  out_features: 6

regressor:
  out_features: 6
  noise: 3.0e-4
  lr: 1.0e-5
  weight_decay: 0.001
  edge_type: knn
  min_dist: 0
  n_neighbours: 5
  edge_weight: True
  fully_connected: True
  self_loop: False
  undirected: False

trainer:
  check_val_every_n_epoch: 1
  max_epochs: 10
  deterministic: True
  num_sanity_val_steps: 2
  limit_train_batches: 1.0 # Default 1.0
  precision: 32 # Default. Only available on GPU.
  val_check_interval: 0.50 # Default 1.0

logger:
  offline: False
  version: full_run_02
  project: waymo_forwardmodel

misc:
  seed: 1
  model_type: mlp_full_forward_model
  dm_type: OneStepWaymoDataModule
  regressor_type: OneStepModule
  checkpoint: False
  train: True
  continue_training: null
