datamodule:
  batch_size: 128
  shuffle: True
  val_batch_size: 64

model:
  hidden_size: 128
  dropout: 0.0
  latent_edge_features: 128
  node_features: 15
  edge_features: 1
  rounds: 5
  shared_params: False
  out_features: 7

regressor:
  out_features: 7
  noise: 1.0e-2
  lr: 1.0e-4
  weight_decay: 0.01
  edge_type: knn
  min_dist: 7
  n_neighbours: 15
  edge_weight: True
  fully_connected: True
  self_loop: False
  undirected: False
  normalise: False
  node_features: 15
  edge_features: 1

trainer:
  check_val_every_n_epoch: 1
  max_epochs: 5
  deterministic: True
  num_sanity_val_steps: 2
#  limit_train_batches: 0.01 # Default 1.0
  precision: 32 # Default. Only available on GPU.
  val_check_interval: 0.50 # Default 1.0
  gpus: 1

logger:
  offline: False
  version: mpnn_08
  project: waymo_mpnn

misc:
  seed: 1
  model_type: mpnn_forward_model
  dm_type: OneStepWaymoDataModule
  regressor_type: OneStepModule
  checkpoint: False
  train: True
  continue_training: null
