datamodule:
  batch_size: 32
  shuffle: True
  val_batch_size: 32

model:
  hidden_size: 128
  dropout: 0.5
  edge_features: 1
  node_features: 15
  skip: True
  rnn_size: 64
  num_layers: 1
  latent_edge_features: 32
  out_features: 7

regressor:
  out_features: 7
  noise: null
  lr: 1.0e-4
  weight_decay: 0.0001
  edge_type: distance
  min_dist: 10
  n_neighbours: 15
  edge_weight: True
  fully_connected: False
  self_loop: False
  undirected: False
  normalise: True
  teacher_forcing: True
  teacher_forcing_ratio: 0.3
  rnn_type: GRU
  node_features: 15
  edge_features: 1

trainer:
  check_val_every_n_epoch: 1
  max_epochs: 3
  deterministic: True
  num_sanity_val_steps: 2
#  limit_train_batches: 0.01 # Default 1.0
  precision: 32 # Default. Only available on GPU.
  val_check_interval: 0.50 # Default 1.0
  gpus: 1

logger:
  offline: False
  version: rnn_04
  project: waymo_rec_forwardmodel

misc:
  seed: 1
  model_type: rnn_node_forward_model
  dm_type: SequentialWaymoDataModule
  regressor_type: SequentialModule
  checkpoint: False
  train: True
  continue_training: null
